version: '3'
services:
  app:
    user: root
    container_name: data_project
    build:
      context: .
    image: dev
    working_dir: /opt/app
    volumes:
      - ~/.aws/:/root/.aws/
      - .:/opt/app